//data creation from json file

var data = ({
    "date": new Date(),
    "company": {
        "name": "French Village LTD",
        "type": "Bakery",
        "status": "Active",
        "shopStatus": "Open",
        "dateOpened": new Date('2013-09-23T00:00:00'),
        "daysOpen": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        "employeesOnShift": 4,
        "customersVisit": 141,
        "vendorSales": 23,
        "socialPosts": 232,
        "visits": [],
        "monthsRun": [],
        "monthlyBalance": [],
        "monthlyProfit": [],
        "monthlyLoss": [],
        "gb": [],
        "vbs": [],
        "rc": [],
        "rcg": [],
        "rvg": [],
        "pb": [],
        "rwcs": [],
        "sb": [],
        "pd": [],
        "rrc": [],
        "bc": [],
        "mac": [],
        "fvb": [],
        "jdb": [],



        "Employees": [

            {
                "employeeName": "Monica Geller",
                "status": "Active",
                "startDate": new Date('2013-09-23T00:00:00'),
                "lastPayriseDate": new Date('2022-04-01T00:00:00'),
                "leaveStatus": null,
                "employeeType": "Director",
                "shiftStatus": true,
                "contract": "FT",
                "workingHours": 37.5,
                "workingDays": [1, 2, 3, 4, 5],
                "leaveEntitlement": 210,
                "leaveTaken": 80.5,
                "sickDays": 1,
                "overtime": 0,
                "gender": "F",
                "salary": 38000,
                "salaryPerDay": 146.15,
                "deductions": 0.0,
                "unionMember": false,
                "employeeBenefits": true,
                "employeeSatisfaction": {
                    "satSurveyReceived": null,
                    "satSurveyCompleted": null,
                    "workerSatisfactionRating": null
                },
                "productivityRating": null

            },
            {
                "employeeName": "Ross Geller",
                "status": "Active",
                "startDate": new Date('2013-09-23T00:00:00'),
                "lastPayriseDate": new Date('2021-04-01T00:00:00'),
                "leaveStatus": null,
                "employeeType": "Director",
                "shiftStatus": true,
                "contract": "FT",
                "workingHours": 37.5,
                "workingDays": [1, 2, 3, 4, 5],
                "leaveEntitlement": 210,
                "leaveTaken": 52,
                "sickDays": 0,
                "overtime": 0,
                "overtimePay": 0,
                "gender": "M",
                "salary": 38000,
                "salaryPerDay": 146.15,
                "deductions": 0.0,
                "unionMember": false,
                "employeeBenefits": true,
                "employeeSatisfaction": {
                    "satSurveyReceived": null,
                    "satSurveyCompleted": null,
                    "workerSatisfactionRating": null
                },
                "productivityRating": null
            },
            {
                "employeeName": "Chandler Bing",
                "status": "Active",
                "startDate": new Date('2014-10-01T00:00:00'),
                "lastPayriseDate": new Date('2021-10-01T00:00:00'),
                "leaveStatus": null,
                "employeeType": "Administration",
                "shiftStatus": true,
                "contract": "FT",
                "workingHours": 37.5,
                "workingDays": [1, 2, 3, 4, 5],
                "leaveEntitlement": 210,
                "leaveTaken": 32,
                "sickDays": 2,
                "overtime": 0,
                "overtimePay": 0,
                "gender": "M",
                "salary": 28500,
                "salaryPerDay": 109.62,
                "deductions": 0.0,
                "unionMember": false,
                "employeeBenefits": true,
                "employeeSatisfaction": {
                    "satSurveyReceived": true,
                    "satSurveyCompleted": true,
                    "workerSatisfactionRating": 9.0
                },
                "productivityRating": 8
            },
            {
                "employeeName": "Phoebe Buffay",
                "status": "Active",
                "startDate": new Date('2018-06-22T00:00:00'),
                "lastPayriseDate": null,
                "leaveStatus": null,
                "employeeType": "Social Media Manager",
                "shiftStatus": true,
                "contract": "PT",
                "workingHours": 20,
                "workingDays": [2, 4, 5],
                "leaveEntitlement": 126,
                "leaveTaken": 28,
                "sickDays": 0,
                "overtime": 0,
                "overtimePay": 0,
                "gender": "F",
                "salary": 16200,
                "salaryPerDay": 104.00,
                "deductions": 0.0,
                "unionMember": true,
                "employeeBenefits": true,
                "employeeSatisfaction": {
                    "satSurveyReceived": true,
                    "satSurveyCompleted": true,
                    "workerSatisfactionRating": 8.7
                },
                "productivityRating": 6
            },
            {
                "employeeName": "Rachel Green",
                "status": "Active",
                "startDate": new Date('2014-02-13T00:00:00'),
                "lastPayriseDate": new Date('2022-02-01T00:00:00'),
                "leaveStatus": null,
                "employeeType": "General Manager",
                "shiftStatus": true,
                "contract": "FT",
                "workingHours": 37.5,
                "workingDays": [2, 3, 4, 5, 6],
                "leaveEntitlement": 210,
                "leaveTaken": 33,
                "sickDays": 1,
                "overtime": 0,
                "overtimePay": 0,
                "gender": "F",
                "salary": 24500,
                "salaryPerDay": 94.23,
                "deductions": 0.0,
                "unionMember": true,
                "employeeBenefits": true,
                "employeeSatisfaction": {
                    "satSurveyReceived": true,
                    "satSurveyCompleted": true,
                    "workerSatisfactionRating": 8.8
                },
                "productivityRating": 9
            },
            {
                "employeeName": "Joey Tribbiani",
                "status": "Active",
                "startDate": new Date('2018-04-18T00:00:00'),
                "lastPayriseDate": new Date('2022-04-06T00:00:00'),
                "leaveStatus": null,
                "employeeType": "Team Lead",
                "shiftStatus": false,
                "contract": "PT",
                "workingHours": 22.5,
                "workingDays": [1, 4, 5, 6],
                "leaveEntitlement": 126,
                "leaveTaken": 42.5,
                "sickDays": 3,
                "overtime": 0,
                "overtimePay": 0,
                "gender": "M",
                "salary": 13000,
                "salaryPerDay": 83.33,
                "deductions": 0.0,
                "unionMember": true,
                "employeeBenefits": false,
                "employeeSatisfaction": {
                    "satSurveyReceived": true,
                    "satSurveyCompleted": true,
                    "workerSatisfactionRating": 8.2
                },
                "productivityRating": 7
            },
            {
                "employeeName": "Carol Willick",
                "status": "Active",
                "startDate": new Date('2014-01-15T00:00:00'),
                "lastPayriseDate": new Date('2022-01-15T00:00:00'),
                "leaveStatus": null,
                "employeeType": "Baker",
                "shiftStatus": true,
                "contract": "FT",
                "workingHours": 37.5,
                "workingDays": [2, 3, 4, 5, 6],
                "leaveEntitlement": 210,
                "leaveTaken": 92.5,
                "sickDays": 1,
                "overtime": 0,
                "overtimePay": 0,
                "gender": "F",
                "salary": 24000,
                "salaryPerDay": 92.40,
                "deductions": 0.0,
                "unionMember": false,
                "employeeBenefits": true,
                "employeeSatisfaction": {
                    "satSurveyReceived": true,
                    "satSurveyCompleted": true,
                    "workerSatisfactionRating": 9.2
                },
                "productivityRating": 9
            },
            {
                "employeeName": "Susan Bunch",
                "status": "Active",
                "startDate": new Date('2016-08-02T00:00:00'),
                "lastPayriseDate": new Date('2021-08-02T00:00:00'),
                "leaveStatus": null,
                "employeeType": "Baker",
                "shiftStatus": true,
                "contract": "PT",
                "workingHours": 30,
                "workingDays": [2, 3, 4, 5],
                "leaveEntitlement": 168,
                "leaveTaken": 32,
                "sickDays": 0,
                "overtime": 0,
                "overtimePay": 0,
                "gender": "F",
                "salary": 22000,
                "salaryPerDay": 105.75,
                "deductions": 0.0,
                "unionMember": true,
                "employeeBenefits": false,
                "employeeSatisfaction": {
                    "satSurveyReceived": true,
                    "satSurveyCompleted": true,
                    "workerSatisfactionRating": 9.0
                },
                "productivityRating": 7

            },
            {
                "employeeName": "Janice Hosenstein",
                "status": "Active",
                "startDate": new Date('2014-03-18T00:00:00'),
                "lastPayriseDate": new Date('2019-10-01T00:00:00'),
                "leaveStatus": null,
                "employeeType": "Store Assistant",
                "shiftStatus": true,
                "contract": "FT",
                "workingHours": 37.5,
                "workingDays": [1, 2, 3, 4, 5, 6],
                "leaveEntitlement": 210,
                "leaveTaken": 102,
                "sickDays": 4,
                "overtime": 0,
                "overtimePay": 0,
                "gender": "F",
                "salary": 17550,
                "salaryPerDay": 67.60,
                "deductions": 0.0,
                "unionMember": true,
                "employeeBenefits": true,
                "employeeSatisfaction": {
                    "satSurveyReceived": true,
                    "satSurveyCompleted": true,
                    "workerSatisfactionRating": 8.0
                },
                "productivityRating": 6
            },
            {
                "employeeName": "Mike Hannigan",
                "status": "Active",
                "startDate": new Date('2019-02-23T00:00:00'),
                "lastPayriseDate": null,
                "leaveStatus": null,
                "employeeType": "Store Assistant",
                "shiftStatus": false,
                "contract": "PT",
                "workingHours": 22.5,
                "workingDays": [2, 3, 6],
                "leaveEntitlement": 126,
                "leaveTaken": 60,
                "sickDays": 3,
                "overtime": 0,
                "overtimePay": 0,
                "gender": "M",
                "salary": 10530,
                "salaryPerDay": 67.66,
                "deductions": 0.0,
                "unionMember": false,
                "employeeBenefits": true,
                "employeeSatisfaction": {
                    "satSurveyReceived": true,
                    "satSurveyCompleted": true,
                    "workerSatisfactionRating": 7.8
                },
                "productivityRating": 5
            },
            {
                "employeeName": "Richard Burke",
                "status": "Active",
                "startDate": new Date('2020-12-08T00:00:00'),
                "lastPayriseDate": null,
                "leaveStatus": null,
                "employeeType": "Store Assistant",
                "shiftStatus": true,
                "contract": "PT",
                "workingHours": 10,
                "workingDays": [1, 5, 6],
                "leaveEntitlement": 84,
                "leaveTaken": 15,
                "sickDays": 0,
                "overtime": 0,
                "overtimePay": 0,
                "gender": "M",
                "salary": 7020,
                "salaryPerDay": 67.50,
                "deductions": 0.0,
                "unionMember": true,
                "employeeBenefits": true,
                "employeeSatisfaction": {
                    "satSurveyReceived": true,
                    "satSurveyCompleted": true,
                    "workerSatisfactionRating": 8.6
                },
                "productivityRating": 9
            },
            {
                "employeeName": "Alice Knight",
                "status": "Active",
                "startDate": new Date('2015-07-04T00:00:00'),
                "lastPayriseDate": new Date('2018-09-25T00:00:00'),
                "leaveStatus": null,
                "employeeType": "Store Assistant",
                "shiftStatus": true,
                "contract": "PT",
                "workingHours": 7.5,
                "workingDays": [6],
                "leaveEntitlement": 42,
                "leaveTaken": 7.5,
                "sickDays": 0,
                "overtime": 0,
                "overtimePay": 0,
                "gender": "F",
                "salary": 3510,
                "salaryPerDay": 67.50,
                "deductions": 0.0,
                "unionMember": true,
                "employeeBenefits": true,
                "employeeSatisfaction": {
                    "satSurveyReceived": true,
                    "satSurveyCompleted": true,
                    "workerSatisfactionRating": 7.2
                },
                "productivityRating": 6
            }


        ],

        "Products": [
            {
                "key": 0,
                "productName": "German Biscuits",
                "yearCreated": 2014,
                "numInStock": 112,
                "outOfStock": false,
                "bakedEachTime": 30,
                "timeToBake": 1,
                "numRawMaterialsPerBake": 10,
                "productSalePrice": 6.50,
                "discount": 0.00,
                "packagingCost": 0.04,
                "productionCost": 0.90,
                "purchasedByVendor": 50,
                "vendorPrice": 5.00,
                "volumeMadePerYear": 3120,
                "volumeSoldPerYear": 3020,
                "totalPackagingCost": 2808,
                "totalSale": 14040,
                "profit": 11232,
                "bakingFinishTime": new Date()
            },
            {
                "key": 1,
                "productName": "Vegan Brownie Slab",
                "lengthOfAvailability": 2,
                "numInStock": 24,
                "outOfStock": false,
                "bakedEachTime": 30,
                "timeToBake": 1,
                "numRawMaterialsPerBake": 15,
                "productSalePrice": 7.50,
                "discount": 0.00,
                "packagingCost": 0.07,
                "productionCost": 2.90,
                "purchasedByVendor": 25,
                "vendorPrice": 5.50,
                "volumeMadePerYear": 1440,
                "volumeSoldPerYear": 1422,
                "totalPackagingCost": 4176,
                "totalSale": 9243,
                "profit": 5067,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 2,
                "productName": "Raspberry Creams",
                "lengthOfAvailability": 1,
                "numInStock": 2,
                "outOfStock": false,
                "bakedEachTime": 50,
                "timeToBake": 2,
                "numRawMaterialsPerBake": 7,
                "productSalePrice": 4.30,
                "discount": 0.00,
                "packagingCost": 0.04,
                "productionCost": 0.40,
                "purchasedByVendor": 45,
                "vendorPrice": 3.80,
                "volumeMadePerYear": 3120,
                "volumeSoldPerYear": 3100,
                "totalPackagingCost": 1248,
                "totalSale": 10296,
                "profit": 9048,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 3,
                "productName": "Raspberry and White Chocolate Gateau",
                "yearCreated": 2014,
                "numInStock": 21,
                "outOfStock": false,
                "bakedEachTime": 30,
                "timeToBake": 2,
                "numRawMaterialsPerBake": 15,
                "productSalePrice": 18.00,
                "discount": 0.00,
                "packagingCost": 0.08,
                "productionCost": 6.80,
                "purchasedByVendor": 20,
                "vendorPrice": 15.50,
                "volumeMadePerYear": 720,
                "volumeSoldPerYear": 620,
                "totalPackagingCost": 4896,
                "totalSale": 11520,
                "profit": 6624,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 4,
                "productName": "Red Velvet Gateau",
                "yearCreated": 2015,
                "numInStock": 18,
                "outOfStock": false,
                "bakedEachTime": 30,
                "timeToBake": 3,
                "numRawMaterialsPerBake": 12,
                "productSalePrice": 16.00,
                "discount": 0.00,
                "packagingCost": 0.08,
                "productionCost": 7.20,
                "purchasedByVendor": 15,
                "vendorPrice": 11.50,
                "volumeMadePerYear": 480,
                "volumeSoldPerYear": 472,
                "totalPackagingCost": 3456,
                "totalSale": 7552,
                "profit": 4096,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 5,
                "productName": "Pavlova Base",
                "yearCreated": 2016,
                "numInStock": 9,
                "outOfStock": false,
                "bakedEachTime": 30,
                "timeToBake": 1,
                "numRawMaterialsPerBake": 4,
                "productSalePrice": 9.50,
                "discount": 0.00,
                "packagingCost": 0.05,
                "productionCost": 2.30,
                "purchasedByVendor": 15,
                "vendorPrice": 8.50,
                "volumeMadePerYear": 384,
                "volumeSoldPerYear": 354,
                "totalPackagingCost": 883.20,
                "totalSale": 3648,
                "profit": 2764,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 6,
                "productName": "Raspberry and White Chocolate Scones",
                "yearCreated": 2014,
                "numInStock": 62,
                "outOfStock": false,
                "bakedEachTime": 40,
                "timeToBake": 1.5,
                "numRawMaterialsPerBake": 8,
                "productSalePrice": 4.00,
                "discount": 0.00,
                "packagingCost": 0.04,
                "productionCost": 0.20,
                "purchasedByVendor": 45,
                "vendorPrice": 2.80,
                "volumeMadePerYear": 3360,
                "volumeSoldPerYear": 3350,
                "totalPackagingCost": 672,
                "totalSale": 13440,
                "profit": 12768,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 7,
                "productName": "Soda Bread",
                "lengthOfAvailability": 3,
                "numInStock": 46,
                "outOfStock": false,
                "bakedEachTime": 40,
                "timeToBake": 1.5,
                "numRawMaterialsPerBake": 8,
                "productSalePrice": 2.80,
                "discount": 0.00,
                "packagingCost": 0.01,
                "productionCost": 0.15,
                "purchasedByVendor": 40,
                "vendorPrice": 1.80,
                "volumeMadePerYear": 1920,
                "volumeSoldPerYear": 1900,
                "totalPackagingCost": 288,
                "totalSale": 5376,
                "profit": 5088,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 8,
                "productName": "12 Puddle Donuts",
                "lengthOfAvailability": 2,
                "numInStock": 22,
                "outOfStock": false,
                "bakedEachTime": 35,
                "timeToBake": 3.5,
                "numRawMaterialsPerBake": 15,
                "productSalePrice": 21.00,
                "discount": 0.00,
                "packagingCost": 0.12,
                "productionCost": 5.45,
                "purchasedByVendor": 15,
                "vendorPrice": 15.50,
                "volumeMadePerYear": 2160,
                "volumeSoldPerYear": 2148,
                "totalPackagingCost": 11772,
                "totalSale": 45108,
                "profit": 5067,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 9,
                "productName": "Raspberry Ruffle Cheesecake",
                "yearCreated": 2016,
                "numInStock": 9,
                "outOfStock": false,
                "bakedEachTime": 30,
                "timeToBake": 1.75,
                "numRawMaterialsPerBake": 12,
                "productSalePrice": 19.95,
                "discount": 2.50,
                "packagingCost": 0.10,
                "productionCost": 6.30,
                "purchasedByVendor": 25,
                "vendorPrice": 13.50,
                "volumeMadePerYear": 2400,
                "volumeSoldPerYear": 2382,
                "totalPackagingCost": 15120,
                "totalSale": 44900.70,
                "profit": 29780.70,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 10,
                "productName": "Biscoff Cheesecake",
                "yearCreated": 2019,
                "numInStock": 3,
                "outOfStock": false,
                "bakedEachTime": 25,
                "timeToBake": 2,
                "numRawMaterialsPerBake": 11,
                "productSalePrice": 18.95,
                "discount": 2.50,
                "packagingCost": 0.10,
                "productionCost": 6.30,
                "purchasedByVendor": 25,
                "vendorPrice": 12.50,
                "volumeMadePerYear": 2400,
                "volumeSoldPerYear": 2382,
                "totalPackagingCost": 15120,
                "totalSale": 44900.70,
                "profit": 29780.70,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 11,
                "productName": "Mint Aero Cheesecake",
                "yearCreated": 2017,
                "numInStock": 3,
                "outOfStock": false,
                "bakedEachTime": 30,
                "timeToBake": 1.75,
                "numRawMaterialsPerBake": 9,
                "productSalePrice": 18.95,
                "discount": 2.50,
                "packagingCost": 0.10,
                "productionCost": 6.30,
                "purchasedByVendor": 25,
                "vendorPrice": 15.50,
                "volumeMadePerYear": 2400,
                "volumeSoldPerYear": 2382,
                "totalPackagingCost": 15120,
                "totalSale": 44900.70,
                "profit": 29780.70,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 12,
                "productName": "French Village Biscuits",
                "yearCreated": 2014,
                "numInStock": 43,
                "outOfStock": false,
                "bakedEachTime": 50,
                "timeToBake": 1,
                "numRawMaterialsPerBake": 7,
                "productSalePrice": 4.50,
                "discount": 0.00,
                "packagingCost": 0.04,
                "productionCost": 0.90,
                "purchasedByVendor": 60,
                "vendorPrice": 1.30,
                "volumeMadePerYear": 3840,
                "volumeSoldPerYear": 3830,
                "totalPackagingCost": 3456,
                "totalSale": 24960,
                "profit": 21504,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 13,
                "productName": "Jammiest Dodger Biscuits",
                "yearCreated": 2019,
                "numInStock": 3,
                "outOfStock": false,
                "bakedEachTime": 35,
                "timeToBake": 1,
                "numRawMaterialsPerBake": 11,
                "productSalePrice": 2.00,
                "discount": 0.00,
                "packagingCost": 0.04,
                "productionCost": 1.00,
                "purchasedByVendor": 40,
                "vendorPrice": 1.50,
                "volumeMadePerYear": 4800,
                "volumeSoldPerYear": 4800,
                "totalPackagingCost": 4750,
                "totalSale": 31200,
                "profit": 26400,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 14,
                "productName": "English Muffins",
                "yearCreated": 2018,
                "numInStock": 92,
                "outOfStock": false,
                "bakedEachTime": 35,
                "timeToBake": 1.5,
                "numRawMaterialsPerBake": 9,
                "productSalePrice": 3.50,
                "discount": 0.00,
                "packagingCost": 0.20,
                "productionCost": 0.90,
                "purchasedByVendor": 65,
                "vendorPrice": 3.00,
                "volumeMadePerYear": 3120,
                "volumeSoldPerYear": 3110,
                "totalPackagingCost": 2808,
                "totalSale": 14040,
                "profit": 11232,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 15,
                "productName": "Belfast Baps",
                "yearCreated": 2014,
                "numInStock": 112,
                "outOfStock": false,
                "bakedEachTime": 55,
                "timeToBake": 1,
                "numRawMaterialsPerBake": 6,
                "productSalePrice": 5.50,
                "discount": 0.00,
                "packagingCost": 0.04,
                "productionCost": 0.90,
                "purchasedByVendor": 50,
                "vendorPrice": 4.00,
                "volumeMadePerYear": 3120,
                "volumeSoldPerYear": 3111,
                "totalPackagingCost": 2808,
                "totalSale": 14040,
                "profit": 11232,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 16,
                "productName": "Brioche Rolls",
                "yearCreated": 2015,
                "numInStock": 98,
                "outOfStock": false,
                "bakedEachTime": 40,
                "timeToBake": 1,
                "numRawMaterialsPerBake": 6,
                "productSalePrice": 5.50,
                "discount": 0.00,
                "packagingCost": 0.04,
                "productionCost": 0.90,
                "purchasedByVendor": 50,
                "vendorPrice": 4.00,
                "volumeMadePerYear": 3120,
                "volumeSoldPerYear": 3112,
                "totalPackagingCost": 2808,
                "totalSale": 14040,
                "profit": 11232,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 17,
                "productName": "Buttermilk Pancakes",
                "yearCreated": 2018,
                "numInStock": 110,
                "outOfStock": false,
                "bakedEachTime": 50,
                "timeToBake": 1,
                "numRawMaterialsPerBake": 10,
                "productSalePrice": 3.20,
                "discount": 0.00,
                "packagingCost": 0.04,
                "productionCost": 0.90,
                "purchasedByVendor": 80,
                "vendorPrice": 3.00,
                "volumeMadePerYear": 3120,
                "volumeSoldPerYear": 3118,
                "totalPackagingCost": 2808,
                "totalSale": 14040,
                "profit": 1232,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 18,
                "productName": "Sourdough Loaf",
                "yearCreated": 2014,
                "numInStock": 112,
                "outOfStock": false,
                "bakedEachTime": 40,
                "timeToBake": 1,
                "numRawMaterialsPerBake": 12,
                "productSalePrice": 5.50,
                "discount": 0.00,
                "packagingCost": 0.04,
                "productionCost": 0.90,
                "purchasedByVendor": 50,
                "vendorPrice": 4.00,
                "volumeMadePerYear": 3120,
                "volumeSoldPerYear": 3110,
                "totalPackagingCost": 2808,
                "totalSale": 14040,
                "profit": 11232,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 19,
                "productName": "Lemon Drizzle Loaf Cake",
                "yearCreated": 2018,
                "numInStock": 92,
                "outOfStock": false,
                "bakedEachTime": 30,
                "timeToBake": 2.5,
                "numRawMaterialsPerBake": 10,
                "productSalePrice": 4.50,
                "discount": 0.00,
                "packagingCost": 0.20,
                "productionCost": 0.90,
                "purchasedByVendor": 65,
                "vendorPrice": 3.00,
                "volumeMadePerYear": 3120,
                "volumeSoldPerYear": 3110,
                "totalPackagingCost": 2808,
                "totalSale": 14040,
                "profit": 11232,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 20,
                "productName": "Caramel Slices",
                "yearCreated": 2019,
                "numInStock": 6,
                "outOfStock": false,
                "bakedEachTime": 45,
                "timeToBake": 1.5,
                "numRawMaterialsPerBake": 12,
                "productSalePrice": 5.00,
                "discount": 0.00,
                "packagingCost": 0.04,
                "productionCost": 1.00,
                "purchasedByVendor": 40,
                "vendorPrice": 3.00,
                "volumeMadePerYear": 4800,
                "volumeSoldPerYear": 4750,
                "totalPackagingCost": 2808,
                "totalSale": 31200,
                "profit": 26400,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 21,
                "productName": "Macarons",
                "yearCreated": 2019,
                "numInStock": 6,
                "outOfStock": false,
                "bakedEachTime": 45,
                "timeToBake": 2,
                "numRawMaterialsPerBake": 15,
                "productSalePrice": 5.00,
                "discount": 0.00,
                "packagingCost": 0.04,
                "productionCost": 1.00,
                "purchasedByVendor": 40,
                "vendorPrice": 3.00,
                "volumeMadePerYear": 4800,
                "volumeSoldPerYear": 4756,
                "totalPackagingCost": 2800,
                "totalSale": 31200,
                "profit": 26400,
                "bakingFinishTime": new Date(),
            },
            {
                "key": 22,
                "productName": "Mixed Traybake Box",
                "yearCreated": 2018,
                "numInStock": 9,
                "outOfStock": false,
                "bakedEachTime": 35,
                "timeToBake": 2.5,
                "numRawMaterialsPerBake": 20,
                "productSalePrice": 20.00,
                "discount": 0.00,
                "packagingCost": 0.12,
                "productionCost": 5.45,
                "purchasedByVendor": 15,
                "vendorPrice": 18.50,
                "volumeMadePerYear": 2160,
                "volumeSoldPerYear": 2148,
                "totalPackagingCost": 1772,
                "totalSale": 45108,
                "profit": 7235,
                "bakingFinishTime": new Date(),
            }


        ],

        "AdminManagement": {
            "Bakery": {
                "rawMaterialsStock": 50,
                "rawMaterialsCostPerDelivery": 550.50,
                "scheduleMaterialsDelivery": false,
                "expectedDeliveryDate": new Date(),
                "rawSuppliesDelivered": false,
            },
            "LicencingCosts": {
                "Legal": {
                    "status": "active",
                    "annualCosts": 2500,
                    "billPaymentDue": new Date('2022-04-03T00:00:00'),
                    "billPaid": true,
                },
                "Accounting": {
                    "status": "active",
                    "annualCosts": 1500,
                    "billPaymentDue": new Date('2022-02-31T00:00:00'),
                    "billPaid": true,
                },
                "SecurityCCTV": {
                    "status": "active",
                    "annualCosts": 1200,
                    "billPaymentDue": new Date('2022-12-29T00:00:00'),
                    "billPaid": false,
                },
                "StreetDisplayLicence": {
                    "status": "active",
                    "annualCosts": 300,
                    "billPaymentDue": new Date('2022-08-20T00:00:00'),
                    "billPaid": false,
                },
                "MusicLicence": {
                    "status": "active",
                    "annualCosts": 300,
                    "billPaymentDue": new Date('2022-04-01T00:00:00'),
                    "billPaid": true,
                }
            },

            "InsuranceCosts": {
                "EmployeeLiability": {
                    "status": "active",
                    "annualCosts": 2500,
                    "billPaymentDue": new Date('2022-02-01T00:00:00'),
                    "billPaid": true,
                },
                "PublicLiability": {
                    "status": "active",
                    "annualCosts": 280,
                    "billPaymentDue": new Date('2022-02-01T00:00:00'),
                    "billPaid": true,
                },
                "ContentsInsurance": {
                    "status": "active",
                    "annualCosts": 480,
                    "billPaymentDue": new Date('2022-06-01T00:00:00'),
                    "billPaid": false,
                }
            },

            "Compliance": {
                "companyHouseDueDate": new Date('2022-07-10T00:00:00'),
                "companyHouseFileDate": new Date(),
                "monthsLate": 0,
                "reminderReceived": false,
                "generalFee": 13,
                "penaltyFeeOneMonth": 150,
                "penaltyFeeThreeMonths": 375,
                "penaltyFeeSixMonths": 750,
                "penaltyFeeSixMonthsPlus": 1500
            },

            "Management": {
                "EmployeeSatisfaction": {
                    "annualSurveyDate": new Date('2022-08-29T00:00:00'),
                    "surveySent": false,
                    "surveySentDate": new Date(),
                    "reminderSent": false,
                    "surveyRemindersSentDate": new Date(),
                    "allSurveysReceived": false
                },
                "Stock": {
                    "reminderToKitchen": false
                },
                "Vendor": {
                    "vendorName": "Ward's Local",
                    "vendorStatus": "active",
                    "vendorReminderToKitchen": false,
                    "vendorProductsDelivered": false,
                    "vendorPaymentReminderSent": false,
                    "vendorLateReminderSent": false,
                    "vendorLateFee": 15.00,
                    "vendorCurrentBill": 0.00,
                    "vendorPaymentReceived": false,
                    "totalReceivedFromVendor": 6542.00
                }
            }


        },

        "Resources": {
            "ShopCosts": {
                "ShopInsurance": {
                    "status": "active",
                    "regularity": "monthly",
                    "costs": 50.50,
                    "billDayDue": new Date('2022-05-25T00:00:00'),
                    "billPaid": false,
                },
                "Electricity": {
                    "status": "active",
                    "regularity": "monthly",
                    "costs": 62.08,
                    "billDayDue": new Date('2022-06-02T00:00:00'),
                    "billPaid": false,
                },
                "Rates": {
                    "status": "active",
                    "regularity": "yearly",
                    "costs": 2200,
                    "billPaymentDue": new Date('2022-09-23T00:00:00'),
                    "billPaid": false,
                },
                "Mortgage": {
                    "status": "active",
                    "regularity": "monthly",
                    "costs": 1450,
                    "billDayDue": new Date('2022-06-15T00:00:00'),
                    "billPaid": false,
                },
                "Cleaning": {
                    "status": "active",
                    "regularity": "monthly",
                    "costs": 56,
                    "billDayDue": new Date('2022-06-10T00:00:00'),
                    "billPaid": false,
                },
                "Telecoms": {
                    "status": "active",
                    "regularity": "monthly",
                    "costs": 68,
                    "billDayDue": new Date('2022-06-23T00:00:00'),
                    "billPaid": false,
                },
                "Stationary": {
                    "status": "active",
                    "regularity": "adhoc",
                    "costs": 30,
                    "billPaymentDue": new Date('2022-06-12T00:00:00'),
                    "billPaid": false,
                },
                "BrandedCarrierBags": {
                    "status": "active",
                    "regularity": "yearly",
                    "costs": 89,
                    "billPaymentDue": new Date('2022-11-18T00:00:00'),
                    "billPaid": false,
                },
                "BusinessCards": {
                    "status": "active",
                    "regularity": "yearly",
                    "costs": 65.95,
                    "billPaymentDue": new Date('2023-01-01T00:00:00'),
                    "billPaid": false,
                },
                "ShopMaintenance": {
                    "status": "active",
                    "regularity": "adhoc",
                    "costs": 45,
                    "billPaymentDue": new Date('2023-01-05T00:00:00'),
                    "billPaid": false,
                },
                "SoftwareEPOS": {
                    "status": "active",
                    "regularity": "yearly",
                    "costs": 520,
                    "billPaymentDue": new Date('2023-02-23T00:00:00'),
                    "billPaid": false,
                },
                "StaffItems": {
                    "status": "active",
                    "regularity": "adhoc",
                    "costs": 28,
                    "billPaymentDue": new Date('2023-02-01T00:00:00'),
                    "billPaid": false,
                }
            },
            "WebsiteCosts": {
                "status": "active",
                "regularity": "yearly",
                "domainCosts": 80,
                "hostingCosts": 420,
                "changeCosts": 250,
                "billPaymentDue": new Date('2023-03-02T00:00:00'),
                "billPaid": false,
            }

        },

        "MarketingCustomerRelations": {
            "HardAdvertisement": {
                "type": "newspaper",
                "status": "active",
                "cost": 450,
                "billPaid": false,
                "datePurchased": new Date('2020-08-16T00:00:00'),
                "dateOfRenewal": new Date('2022-08-16T00:00:00')
            },
            "SoftAdvertisement": {
                "type": "social media package",
                "status": "active",
                "cost": 390,
                "billPaid": true,
                "datePurchased": new Date('2018-04-17T00:00:00'),
                "dateOfRenewal": new Date('2022-08-17T00:00:00')
            },

            "socialMediaPosts": [
                {
                    "platform": "facebook",
                    "dateOfPost": new Date('2022-03-29T00:00:00'),
                    "uniqueViews": 8032,
                    "likes": 3844,
                    "comments": 469
                },
                {
                    "platform": "instagram",
                    "dateOfPost": new Date('2022-02-14T00:00:00'),
                    "uniqueViews": 10322,
                    "likes": 2291,
                    "comments": 227
                },
                {
                    "platform": "website",
                    "dateOfPost": new Date('2022-02-25T00:00:00'),
                    "uniqueViews": 10322,
                    "likes": 2291,
                    "comments": 227
                }
            ]

        },

        "Customers": [
            {
                "name": "Customer A",
                "dateOfVisit": new Date('2022-03-23T00:00:00'),
                "visitedBefore": false,
                "customerStatus": "new",
                "loyaltyCard": true,
                "loyaltyVisitNumber": 1,
                "customerDisc": 0.00,
                "customerDOB": new Date('1994-06-13T00:00:00'),
                "datePaid": new Date('2020-06-26T00:00:00'),
                "birthday": false,
                "numProductsBought": 4,
                "productsBought": ["German Biscuits", "French Village Biscuits", "Soda Bread"],
                "customerBudget": 15.00,
                "socialMediaUser": true,
                "tipAmount": 0.00,
            },
            {
                "name": "Customer B",
                "dateOfVisit": new Date('2022-03-01T00:00:00'),
                "visitedBefore": true,
                "customerStatus": "returning",
                "loyaltyCard": true,
                "loyaltyVisitNumber": 20,
                "customerDisc": 0.10,
                "customerDOB": new Date('1976-03-30T00:00:00'),
                "datePaid": new Date('2021-04-01T00:00:00'),
                "birthday": "false",
                "numProductsBought": 2,
                "productsBought": ["French Village Biscuits", "Soda Bread"],
                "customerBudget": 25.00,
                "socialMediaUser": true,
                "tipAmount": 2.00,
            },
            {
                "name": "Customer C",
                "dateOfVisit": new Date(),
                "visitedBefore": false,
                "customerStatus": "new",
                "loyaltyCard": false,
                "loyaltyVisitNumber": 0,
                "customerDisc": 0.00,
                "customerDOB": new Date('1980-08-23T00:00:00'),
                "datePaid": new Date('2022-08-12T00:00:00'),
                "birthday": "false",
                "numProductsBought": 0,
                "productsBought": [],
                "customerBudget": 30.00,
                "socialMediaUser": true,
                "tipAmount": 1.00,
            },
            {
                "name": "Customer D",
                "dateOfVisit": new Date('2022-04-12T00:00:00'),
                "visitedBefore": true,
                "customerStatus": "returning",
                "loyaltyCard": false,
                "loyaltyVisitNumber": 0,
                "customerDisc": 0.00,
                "customerDOB": new Date('2000-11-13T00:00:00'),
                "datePaid": new Date('2022-01-01T00:00:00'),
                "birthday": "false",
                "numProductsBought": 3,
                "productsBought": ["Caramel Slices", "Sourdough Loaf", "Jammiest Dodger Biscuits"],
                "customerBudget": 23.00,
                "socialMediaUser": true,
                "tipAmount": 5.80,
            },
            {
                "name": "Customer E",
                "dateOfVisit": new Date('2021-05-18T00:00:00'),
                "visitedBefore": true,
                "customerStatus": "returning",
                "loyaltyCard": true,
                "loyaltyVisitNumber": 12,
                "customerDisc": 0.10,
                "customerDOB": new Date('1994-07-03T00:00:00'),
                "datePaid": new Date('2022-01-12T00:00:00'),
                "birthday": "false",
                "numProductsBought": 5,
                "productsBought": ["Caramel Slices", "Sourdough Loaf", "Jammiest Dodger Biscuits", "English Muffins", "Belfast Baps"],
                "customerBudget": 12.00,
                "socialMediaUser": true,
                "tipAmount": 3.50,
            },
            {
                "name": "Customer F",
                "dateOfVisit": new Date('2021-12-12T00:00:00'),
                "visitedBefore": true,
                "customerStatus": "returning",
                "loyaltyCard": false,
                "loyaltyVisitNumber": 0,
                "customerDisc": 0.00,
                "customerDOB": new Date('1997-03-05T00:00:00'),
                "datePaid": new Date('2021-01-22T00:00:00'),
                "birthday": "false",
                "numProductsBought": 5,
                "productsBought": ["Lemon Drizzle Loaf Cake", "Mixed Traybake Box", "Buttermilk Pancakes", "Macarons", "Brioche Rolls"],
                "customerBudget": 20.00,
                "socialMediaUser": true,
                "tipAmount": 10.30,
            },
            {
                "name": "Customer G",
                "dateOfVisit": new Date('2022-05-02T00:00:00'),
                "visitedBefore": true,
                "customerStatus": "returning",
                "loyaltyCard": true,
                "loyaltyVisitNumber": 16,
                "customerDisc": 0.00,
                "customerDOB": new Date('1982-11-10T00:00:00'),
                "datePaid": new Date(),
                "birthday": "false",
                "numProductsBought": 3,
                "productsBought": ["Caramel Slices", "Sourdough Loaf", "Jammiest Dodger Biscuits"],
                "customerBudget": 25.00,
                "socialMediaUser": false,
                "tipAmount": 0.50,
            },
            {
                "name": "Customer H",
                "dateOfVisit": new Date('2021-08-12T00:00:00'),
                "visitedBefore": true,
                "customerStatus": "returning",
                "loyaltyCard": false,
                "loyaltyVisitNumber": 0,
                "customerDisc": 0.00,
                "customerDOB": new Date('2003-06-27T00:00:00'),
                "datePaid": new Date(),
                "birthday": "false",
                "numProductsBought": 1,
                "productsBought": ["Caramel Slices"],
                "customerBudget": 11.00,
                "socialMediaUser": false,
                "tipAmount": 0.00,
            },
            {
                "name": "Customer I",
                "dateOfVisit": new Date(),
                "visitedBefore": false,
                "customerStatus": "new",
                "loyaltyCard": true,
                "loyaltyVisitNumber": 0,
                "customerDisc": 0.00,
                "customerDOB": new Date('1965-02-18T00:00:00'),
                "datePaid": new Date('2020-05-27T00:00:00'),
                "birthday": false,
                "numProductsBought": 0,
                "productsBought": [],
                "customerBudget": 17.00,
                "socialMediaUser": true,
                "tipAmount": 0.00,
            },
            {
                "name": "Customer J",
                "dateOfVisit": new Date('2022-06-18T00:00:00'),
                "visitedBefore": true,
                "customerStatus": "returning",
                "loyaltyCard": true,
                "loyaltyVisitNumber": 55,
                "customerDisc": 0.0,
                "customerDOB": new Date('1962-10-20T00:00:00'),
                "datePaid": new Date('2020-05-01T00:00:00'),
                "birthday": "false",
                "numProductsBought": 5,
                "productsBought": ["English Muffins", "Mint Aero Cheesecake", "12 Puddle Donuts", "Biscoff Cheesecake", "Raspberry and White Chocolate Scones"],
                "customerBudget": 12.00,
                "socialMediaUser": true,
                "tipAmount": 2.50,
            },
            {
                "name": "Customer K",
                "dateOfVisit": new Date('2019-02-18T00:00:00'),
                "visitedBefore": true,
                "customerStatus": "returning",
                "loyaltyCard": true,
                "loyaltyVisitNumber": 32,
                "customerDisc": 0.0,
                "customerDOB": new Date('1962-04-05T00:00:00'),
                "datePaid": new Date('2020-05-07T00:00:00'),
                "birthday": "false",
                "numProductsBought": 5,
                "productsBought": ["English Muffins", "Mint Aero Cheesecake", "12 Puddle Donuts", "Biscoff Cheesecake", "Raspberry and White Chocolate Scones"],
                "customerBudget": 11.00,
                "socialMediaUser": true,
                "tipAmount": 5.50,
            },

        ],

        "Finances": {
            "bankBalance": 20162.92,
            "Turnover": {
                "annualProfit": 22542.00,
                "annualLoss": 5322.80,
                "breakEven": false,
                "bankrupt": false
            },
            "Banking": {
                "Outgoing": {
                    "staffPayRollMonthly": 258100,
                    "staffPayrollYearly": 100500,
                    "supplierCosts": 0.00,
                    "staffPayRollDate": 1
                },
                "Ingoing": {
                    "externalSupplierIncome": 3642.20,
                    "totalProductSaleIncome": 13422.82,
                    "totalTips": 120.30
                }

            }

        }

    }
});